version: '3.8'

services:
  app:
    build: .
    container_name: app
    command: uvicorn app.main:app --host 0.0.0.0 --reload --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
  db:
    image: redis:7.0
    container_name: db
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - 6379:6379

volumes:
  redis-data: